---
- hosts: test-server
  become: true
  tasks:
    - name: update apt
      command: sudo apt-get update
    - name: install docker
      command: sudo apt install -y docker.io
    - name: start docker service
      command: sudo systemctl start docker
    - name: Stop the Docker container if running
      community.docker.docker_container:
      name: insure-me
      state: stopped
      ignore_errors: true
    - name: Remove the Docker container named "insure-me"
      community.docker.docker_container:
      name: insure-me
      state: absent
      ignore_errors: true
    - name: deploy insureme application
      command: sudo docker run -itd -p 8081:8081 --name
        insure-me  mahendra834/insure-me:1.0

